repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: requirements-txt-fixer
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.0
    hooks:
    -   id: ruff
        args:
            - --fix
-   repo: https://github.com/psf/black
    rev: 23.10.0
    hooks:
    -   id: black
-   repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
    -   id: toml-sort
        args:
            - --in-place
            - --all
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
